# SPDX-FileCopyrightText: 2018 Joern Barthel <joern.barthel@kreuzwerker.de>
# SPDX-License-Identifier: Apache-2.0

build: off

clone_folder: c:\gopath\src\github.com\yawn\ykoath

environment:
  GOPATH: c:\gopath
  GO111MODULE: on

stack: go 1.11

before_test:
  - go get -t -v ./...

test_script:
  - go test -coverprofile=coverage.txt -covermode=atomic -parallel 1 -race -tags ci
