# SPDX-FileCopyrightText: 2018 Joern Barthel <joern.barthel@kreuzwerker.de>
# SPDX-License-Identifier: Apache-2.0

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macOS-latest, windows-latest ]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Install dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install -qy libpcsclite-dev

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -coverprofile coverage.txt -covermode atomic -parallel 1 -race -tags ci -v ./...
